/**
 * 会话实体 — 存储智能体会话状态、任务历史和统计信息
 * Session entity — stores agent session state, task history, and statistics
 */
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity('sessions')
export class SessionEntity {
  // 主键，自动生成 UUID / Primary key, auto-generated UUID
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  // 会话标识符（由客户端生成，唯一） / Session identifier (generated by client, unique)
  @Column({ name: 'session_id', length: 100, unique: true })
  sessionId!: string;

  // 会话状态：idle（空闲）、running（运行中）、completed（已完成）、error（错误） / Session status: idle, running, completed, error
  @Column({ type: 'enum', enum: ['idle', 'running', 'completed', 'error'], default: 'idle' })
  status!: string;

  // 当前执行的任务描述 / Current task description
  @Column({ name: 'current_task', type: 'text', nullable: true })
  currentTask!: string | null;

  // 会话历史记录（JSON 格式，包含步骤、观察和错误事件） / Session history (JSON format, contains step, observation, and error events)
  @Column({ type: 'json', nullable: true })
  history!: Array<Record<string, unknown>> | null;

  // 总步骤数 / Total number of steps
  @Column({ name: 'total_steps', type: 'int', default: 0 })
  totalSteps!: number;

  // 总 token 消耗量 / Total token consumption
  @Column({ name: 'total_tokens', type: 'int', default: 0 })
  totalTokens!: number;

  // 创建时间 / Creation timestamp
  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;

  // 更新时间 / Update timestamp
  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;
}
